# servo.yaml with relaxed collision settings

# General parameters
publish_period: 0.01  # seconds
incoming_command_timeout: 0.1  # seconds
num_outgoing_halt_msgs_to_publish: 5
low_pass_filter_coeff: 2.0
joint_limit_margin: 0.1  # radians
use_gazebo: false

# Input settings
command_in_type: speed_units  # or 'unitless' depending on your controller
scale:
  linear: 0.5
  rotational: 0.5
  joint: 0.5

# Robot-specific frames and topics
planning_frame: base_link
ee_frame_name: tool0
robot_link_command_frame: tool0  # Commands in end-effector frame
joint_topic: /joint_states
cartesian_command_in_topic: /servo_server/delta_twist_cmds
joint_command_in_topic: /servo_server/delta_joint_cmds

# Output settings
command_out_topic: /servo_server/command
command_out_type: trajectory_msgs/JointTrajectory
publish_joint_positions: false
publish_joint_velocities: true
publish_joint_accelerations: false

# Move group
move_group_name: manipulator

# Collision checking - RELAXED SETTINGS
check_collisions: true
collision_check_rate: 5  # Reduced from 10 Hz
collision_check_type: threshold_distance
self_collision_proximity_threshold: 0.01  # Reduced from 0.05
scene_collision_proximity_threshold: 0.01  # Reduced from 0.05
collision_distance_safety_factor: 1.0  # Reduced from 1.5
min_allowable_collision_distance: 0.002  # Reduced from 0.01

# Singularities
lower_singularity_threshold: 0.05  # Reduced from 0.1
hard_stop_singularity_threshold: 0.1  # Reduced from 0.2

# Status
status_topic: /servo_server/status